/-
  GIFT Foundations: Lean certificate for two structural lattice / irrep
  results on the compact G_2 manifold K_7.

  Part A — Basis change between the adiabatic K_3 x T^2 x I decomposition
  of harmonic 3-forms and the G_2-irrep decomposition:

      H^3(K_7) = R^77
      adiabatic split:    77 = 35 (s-independent) + 42 (T^2 fiber-coupled)
      G_2-irrep split:    77 = 1 (Lambda^3_1)    + 76 (Lambda^3_27)        (b^1 = 0)
      reconciliation:     35 = 1 (Lambda^3_1, ⟨phi⟩) + 34 (Lambda^3_27 ∩ s-indep)
                          42 = 42 (Lambda^3_27 ∩ s-coupled)

  with the pointwise identity

      dim Lambda^3 R^7 = 35 = C(7,3) = 1 + 7 + 27   (G_2-irrep dimensions).

  Part B — Mukai V_4-invariant Neron-Severi lattice closure:

      G_simple = diag(8, -2, ..., -2)      rank 15, |det| = 2^17
      L_target = H + E_7(-1) + A_1(-1)^6   rank 15, |det| = 2^7

  The ratio 2^17 / 2^7 = 2^10 = (2^5)^2 decomposes virtually as
  2^(2+3) x 2^(2+3) (two halvings in H, three halvings in E_7(-1)).
  By Nikulin (1979) L_target is the unique even lattice with rank 15,
  signature (1, 14), |det| = 2^7, parity δ = 1; hence L_target equals
  NS(X-tilde)^{V_4} for a symplectic V_4 action on K_3 (Mukai 1988,
  Garbagnati-Sarti 2009).

  All theorems below are `Nat` arithmetic, verifiable by `native_decide`.
-/

import GIFT.Core

namespace GIFT.Foundations.G2IrrepLatticeCertificate

/-! ## Part A — G_2-irrep / NK basis change for H^3(K_7) -/

/-! ### Pointwise G_2-irrep dimensions of Λ^3 R^7 -/

/-- Dimension of the trivial G_2 irrep Λ³_1. Generated by the G_2-form φ. -/
def L1_dim : Nat := 1

/-- Dimension of the fundamental G_2 irrep Λ³_7, isomorphic to T*R^7
    via the contraction map X ↦ X ⌟ *φ. -/
def L7_dim : Nat := 7

/-- Dimension of the 27-dim G_2 irrep Λ³_27 (the traceless symmetric
    representation; orthogonal complement of Λ³_1 ⊕ Λ³_7 in Λ³ R^7). -/
def L27_dim : Nat := 27

/-- Pointwise dim of Λ³ R^7 equals the sum of G_2 irrep dimensions. -/
theorem irrep_dims_sum : L1_dim + L7_dim + L27_dim = 35 := by native_decide

/-- C(7, 3) = 35 = pointwise dim of Λ³ R^7 (binomial). -/
theorem irrep_dims_eq_choose : 1 + 7 + 27 = Nat.choose 7 3 := by native_decide

/-! ### Global harmonic counts on closed simply-connected G_2 manifold K_7

For a closed compact 7-manifold with full G_2 holonomy:
- `b^1 = 0` (simply connected)
- `dim Harm Λ³_1 = 1` (the G_2 form itself)
- `dim Harm Λ³_7 = b^1 = 0` (isomorphism Λ³_7 ≅ T*K_7)
- `dim Harm Λ³_27 = b^3 - 1 - b^1 = b^3 - 1`

GIFT target: `b_2 = 21`, `b_3 = 77`. -/

/-- First Betti number of K_7 (simply connected). -/
def b1_K7 : Nat := 0

/-- Second Betti number of GIFT K_7. -/
def b2_K7 : Nat := 21

/-- Third Betti number of GIFT K_7. -/
def b3_K7 : Nat := 77

/-- Harmonic Λ³_1 count = 1 (the G_2 form). -/
def Harm_L1 : Nat := L1_dim

/-- Harmonic Λ³_7 count = b^1 = 0 (Joyce 2000). -/
def Harm_L7 : Nat := b1_K7

/-- Harmonic Λ³_27 count = b_3 - 1 - b^1 = 76. -/
def Harm_L27 : Nat := b3_K7 - Harm_L1 - Harm_L7

theorem Harm_L27_eq_76 : Harm_L27 = 76 := by native_decide

theorem b3_via_irreps : Harm_L1 + Harm_L7 + Harm_L27 = b3_K7 := by native_decide

/-! ### NK adiabatic basis 35 + 42 -/

/-- NK "constant" sector: 3-form classes of H^3(K_7) with an
    s-independent representative in the adiabatic K_3 × T^2 × I local
    model. From `K7_hodge_3form_results.json`: 35 zero modes of the
    1D Hodge Laplacian on s with gap factor 10522×. -/
def nk_constant : Nat := 35

/-- NK "fiber-coupled" sector: 3-form classes of H^3(K_7) coupling to
    the T^2 generators (dθ ∧ ω_α and dψ ∧ ω_α for the 21 extending K_3
    harmonic 2-forms). 21 × 2 = 42 modes. -/
def nk_fiber : Nat := 42

/-- Number of K_3 harmonic 2-forms extending to K_7 (after TCS-killing
    of one form). -/
def k3_extending : Nat := 21

theorem nk_fiber_via_extending : nk_fiber = 2 * k3_extending := by
  native_decide

theorem nk_partition : nk_constant + nk_fiber = b3_K7 := by native_decide

/-! ### Basis change : 35 = 1 + 34, 42 = 42

Globally on a closed s.c. G_2 manifold, `dim Harm Λ³_7 = b^1 = 0`. Hence
the 35 "NK constant" modes split as `1 (Λ³_1, ⟨phi⟩) + 34 (Λ³_27 ∩
s-indep)`, and the 42 "NK fiber-coupled" all sit in `Λ³_27 ∩ s-coupled`. -/

/-- Λ³_27 harmonic split into s-independent portion. -/
def L27_sIndep : Nat := 34

/-- Λ³_27 harmonic split into s-coupled portion (= NK fiber-coupled). -/
def L27_sCoupled : Nat := 42

theorem L27_split : L27_sIndep + L27_sCoupled = Harm_L27 := by native_decide

theorem nk_constant_eq_one_plus_L27sIndep :
    Harm_L1 + L27_sIndep = nk_constant := by native_decide

theorem nk_fiber_eq_L27sCoupled : L27_sCoupled = nk_fiber := by
  native_decide

/-- The basis change reconciliation: NK partition and Donaldson G_2-irrep
    partition are different decompositions of the SAME `H^3(K_7) = R^77`. -/
theorem basis_change_total :
    (Harm_L1 + L27_sIndep) + L27_sCoupled
      = Harm_L1 + Harm_L7 + Harm_L27 := by
  native_decide

/-! ## Part B — Mukai V_4-invariant Neron-Severi Gram closure -/

/-! ### Discriminant arithmetic -/

/-- Determinant of the simple-form template
    `G_simple = diag(8, -2, -2, ..., -2)` (1 + 14 entries, rank 15).
    `|det| = 8 · 2^14 = 2^17 = 131072`. -/
def det_simple_abs : Nat := 8 * 2^14

theorem det_simple_eq_2_pow_17 : det_simple_abs = 2^17 := by native_decide

theorem det_simple_value : det_simple_abs = 131072 := by native_decide

/-- Determinant of the target Mukai V_4-invariant NS lattice
    `L_target = H ⊕ E_7(-1) ⊕ A_1(-1)^6`.
    `|det| = |-1| · |-2| · |(-2)^6| = 1 · 2 · 64 = 128 = 2^7`. -/
def det_target_abs : Nat := 1 * 2 * 64

theorem det_target_eq_2_pow_7 : det_target_abs = 2^7 := by native_decide

theorem det_target_value : det_target_abs = 128 := by native_decide

/-- Discrepancy ratio `2^17 / 2^7 = 2^10 = 1024`. -/
def det_ratio : Nat := det_simple_abs / det_target_abs

theorem det_ratio_eq_2_pow_10 : det_ratio = 2^10 := by native_decide

theorem det_ratio_value : det_ratio = 1024 := by native_decide

/-! ### Rank decomposition of L_target -/

/-- Rank of H (hyperbolic plane). -/
def rank_H : Nat := 2

/-- Rank of E_7(-1). -/
def rank_E7 : Nat := 7

/-- Number of A_1(-1) copies in L_target. -/
def num_A1 : Nat := 6

/-- Rank of A_1(-1)^6. -/
def rank_A1_6 : Nat := num_A1

/-- Rank of L_target = H ⊕ E_7(-1) ⊕ A_1(-1)^6. -/
def rank_target : Nat := rank_H + rank_E7 + rank_A1_6

theorem rank_target_eq_15 : rank_target = 15 := by native_decide

/-- Signature of L_target: (1 positive, 14 negative). -/
def sig_target : Nat × Nat := (1, 14)

theorem sig_target_sum_eq_rank :
    sig_target.1 + sig_target.2 = rank_target := by
  native_decide

/-- Parity δ = 1 (L_target is even but admits an odd-norm class in
    the discriminant form, by the A_1(-1) and E_7(-1) summands). -/
def parity_delta : Nat := 1

/-! ### Saturation index decomposition

The ratio `2^10` does NOT arise from a real lattice saturation
(since `G_simple` is not the Gram of any sub-lattice of `L_target`),
but it factors as `(2^5)^2` with `2^5 = 2^(2+3)` corresponding to:

- 2 halvings in the H block (sub-lattice ⟨2e+2f, e-f⟩ ⊂ H index 4 = 2^2)
- 3 halvings in the E_7 block (A_1(-1)^7 ⊂ E_7(-1) index 8 = 2^3)
-/

/-- Index of `⟨2e+2f, e-f⟩` inside `H` (virtual halvings count = 2). -/
def index_H : Nat := 4

theorem index_H_eq_2_pow_2 : index_H = 2^2 := by native_decide

/-- Index of `A_1(-1)^7` inside `E_7(-1)` (virtual halvings count = 3).
    E_7 contains 7 mutually orthogonal A_1's; the quotient
    `E_7 / A_1^7 ≅ (Z/2)^3` has order 8. -/
def index_E7 : Nat := 8

theorem index_E7_eq_2_pow_3 : index_E7 = 2^3 := by native_decide

/-- Total virtual saturation index `2^5 = 32`. -/
def index_total : Nat := index_H * index_E7

theorem index_total_eq_2_pow_5 : index_total = 2^5 := by native_decide

theorem index_total_squared_eq_ratio :
    index_total * index_total = det_ratio := by
  native_decide

/-! ## Composite certificate -/

set_option linter.dupNamespace false in
structure G2IrrepLatticeCertificate where
  -- Part A: G_2-irrep / NK basis change
  pointwise_irrep_dims_match_35 : Bool
  pointwise_irrep_sum_eq_choose : Bool
  global_harm_L27_eq_76 : Bool
  b3_K7_eq_77 : Bool
  nk_partition_eq_77 : Bool
  basis_change_one_plus_thirtyfour_eq_thirtyfive : Bool
  basis_change_fortytwo_eq_fortytwo : Bool
  -- Part B: Mukai V_4 NS Gram closure
  det_simple_2_pow_17 : Bool
  det_target_2_pow_7 : Bool
  det_ratio_2_pow_10 : Bool
  rank_target_eq_15 : Bool
  signature_target_sum_eq_rank : Bool
  parity_target_delta_eq_1 : Bool
  index_total_eq_2_pow_5 : Bool
  index_squared_eq_ratio : Bool
  deriving DecidableEq, Repr

def g2IrrepLatticeCertificate : G2IrrepLatticeCertificate where
  pointwise_irrep_dims_match_35 := (L1_dim + L7_dim + L27_dim) == 35
  pointwise_irrep_sum_eq_choose :=
    (L1_dim + L7_dim + L27_dim) == Nat.choose 7 3
  global_harm_L27_eq_76 := Harm_L27 == 76
  b3_K7_eq_77 := b3_K7 == 77
  nk_partition_eq_77 := (nk_constant + nk_fiber) == 77
  basis_change_one_plus_thirtyfour_eq_thirtyfive :=
    (Harm_L1 + L27_sIndep) == nk_constant
  basis_change_fortytwo_eq_fortytwo := L27_sCoupled == nk_fiber
  det_simple_2_pow_17 := det_simple_abs == 2^17
  det_target_2_pow_7 := det_target_abs == 2^7
  det_ratio_2_pow_10 := det_ratio == 2^10
  rank_target_eq_15 := rank_target == 15
  signature_target_sum_eq_rank :=
    (sig_target.1 + sig_target.2) == rank_target
  parity_target_delta_eq_1 := parity_delta == 1
  index_total_eq_2_pow_5 := index_total == 2^5
  index_squared_eq_ratio := (index_total * index_total) == det_ratio

theorem g2IrrepLatticeCertificate_all :
    g2IrrepLatticeCertificate.pointwise_irrep_dims_match_35 = true ∧
    g2IrrepLatticeCertificate.pointwise_irrep_sum_eq_choose = true ∧
    g2IrrepLatticeCertificate.global_harm_L27_eq_76 = true ∧
    g2IrrepLatticeCertificate.b3_K7_eq_77 = true ∧
    g2IrrepLatticeCertificate.nk_partition_eq_77 = true ∧
    g2IrrepLatticeCertificate.basis_change_one_plus_thirtyfour_eq_thirtyfive = true ∧
    g2IrrepLatticeCertificate.basis_change_fortytwo_eq_fortytwo = true ∧
    g2IrrepLatticeCertificate.det_simple_2_pow_17 = true ∧
    g2IrrepLatticeCertificate.det_target_2_pow_7 = true ∧
    g2IrrepLatticeCertificate.det_ratio_2_pow_10 = true ∧
    g2IrrepLatticeCertificate.rank_target_eq_15 = true ∧
    g2IrrepLatticeCertificate.signature_target_sum_eq_rank = true ∧
    g2IrrepLatticeCertificate.parity_target_delta_eq_1 = true ∧
    g2IrrepLatticeCertificate.index_total_eq_2_pow_5 = true ∧
    g2IrrepLatticeCertificate.index_squared_eq_ratio = true := by
  native_decide

/-- Human-readable status. -/
def g2IrrepLatticeStatus : String :=
  "G_2-irrep / Mukai V_4 lattice certificate: Λ³ R^7 = 1 + 7 + 27 = 35 (G_2 pointwise); H^3(K_7) = 1 + 76 (Donaldson) = 35 + 42 (NK adiabatic); L_target = H ⊕ E_7(-1) ⊕ A_1(-1)^6 (rank 15, |det| 2^7, sig (1,14), δ = 1)."

theorem g2IrrepLatticeStatus_nonempty :
    g2IrrepLatticeStatus.length > 0 := by
  native_decide

end GIFT.Foundations.G2IrrepLatticeCertificate
